apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c.c 
  janus-idp.io/tekton: c.c
  backstage.io/kubernetes-id: c.c
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c.c
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  